### PR TITLE
Make environment variables more visible

### PR DESCRIPTION
**Pull request by lgorenstein**
Mention relevant `AT_****` variables in [USAGE.md](USAGE.md) and in the `--help` output.

### CODE REVIEW

**Comment by brockpalen** [comment]
The ENV vars were documented in the INSTALL page is that acceptable or was that not useful?

I personally prefer that this is only documented (and thus maintained)  in a single location.  I don't care which location.

**Comment by lgorenstein** [comment]
Heh, I went straight for `singularity/README.md` and completely missed anything inside `INSTALL.md` 🤦 

OTOH, this may serve as an anecdotal testament to TIMTOWTDI and to the power of cross-referencing.  How about this: keep INSTALL.md as an authoritative source of truth on the variables, have a hyperlink to that section in USAGE.md?  If you are ok with this solution, I'll make it happen.

**Comment by brockpalen** [comment]
Yeah crosslinking should address it thanks!

**Comment by lgorenstein** [comment]
Here we go, how's this?

**Comment by brockpalen** [comment]
Yeah this looks good

**Comment by lgorenstein** [comment]
Brock, at your convenience, would you consider tagging this with 0.15.5 (as there was a small change to main script mentioning environment variables in --help)?

I can build my own singularity container :), just wanted to have a numbered version for the sake of modulefile.

**Comment by brockpalen** [comment]
I just released v0.15.5  it also fixes two bugs.  Only one I think you care about because you don't use archivescan for your HPSS.

**Comment by lgorenstein** [comment]
Excellent, thank you very much!  Pulled it down.

**Pull request merged**
